apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc-viewer-backend
  labels:
    app.kubernetes.io/name: dvc-viewer-backend
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: backend
    app.kubernetes.io/company: iterative.ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dvc-viewer-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dvc-viewer-backend
    spec:
      containers:
      - name: backend
        image: dvc-viewer-backend 
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health?format=json
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 25
          timeoutSeconds: 20
        env:
        # Secrets
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: redis_url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: redis_url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: database_url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: secret_key
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: github_client_id
        - name: GITHUB_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: github_client_secret
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: dvc-viewer-secret
              key: github_webhook_secret
        envFrom:
        - configMapRef:
            name: dvc-viewer-config
