apiVersion: v1
kind: Service
metadata:
  name: dvc-viewer-backend
  labels:
    app.kubernetes.io/name: dvc-viewer-backend
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: backend
    app.kubernetes.io/company: iterative.ai
spec:
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: dvc-viewer-backend
