apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./redis/deployment.yaml
- ./redis/service.yaml
- ./postgres/deployment.yaml
- ./postgres/pv.yaml
- ./postgres/pvc.yaml
- ./postgres/service.yaml
