apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc-viewer-ui
  labels:
    app.kubernetes.io/name: dvc-viewer-ui
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: ui
    app.kubernetes.io/company: iterative.ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dvc-viewer-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dvc-viewer-ui
    spec:
      containers:
      - name: ui
        image: dvc_viewer/ui
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 25
          timeoutSeconds: 10
        envFrom:
        - configMapRef:
            name: dvc-viewer-config
