apiVersion: v1
kind: Service
metadata:
  name: dvc-viewer-ui
  labels:
    app.kubernetes.io/name: dvc-viewer-ui
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: ui
    app.kubernetes.io/company: iterative.ai
spec:
  ports:
  - name: ui
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: dvc-viewer-ui
