apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc-viewer-redis
  labels:
    app.kubernetes.io/name: dvc-viewer-redis
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: redis
    app.kubernetes.io/company: iterative.ai
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dvc-viewer-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dvc-viewer-redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.6-alpine
        ports:
        - containerPort: 6379
