apiVersion: v1
kind: Service
metadata:
  name: dvc-viewer-redis
  labels:
    app.kubernetes.io/name: dvc-viewer-redis
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: redis
    app.kubernetes.io/company: iterative.ai
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: dvc-viewer-redis
