apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc-viewer-postgres
  labels:
    app.kubernetes.io/name: dvc-viewer-postgres
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: postgres
    app.kubernetes.io/company: iterative.ai
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dvc-viewer-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dvc-viewer-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.2-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          value: dvc
        - name: POSTGRES_PASSWORD
          value: for_development_purpose
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: dvc-viewer-postgres-pv-claim
