apiVersion: v1
kind: PersistentVolume
metadata:
  name: dvc-viewer-postgres-pv
  labels:
    app.kubernetes.io/name: dvc-viewer-postgres-pv
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: postgres
    app.kubernetes.io/company: iterative.ai
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/hostpath_pv/dvc-viewer-pv-1
