version: "3.4"

services:
  api:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    image: ${STUDIO_BACKEND_IMAGE}:${STUDIO_RELEASE_VERSION}
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      SOCIAL_AUTH_REDIRECT_IS_HTTPS: "${SOCIAL_AUTH_REDIRECT_IS_HTTPS:-False}"
      SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: "localhost:3000,localhost:8000"
      API_URL: ${API_URL:-http://localhost:8000/api}

      <<: &base_settings
        CELERY_BROKER_URL: ${REDIS_URL:-redis://redis:6379}
        CELERY_RESULT_BACKEND: ${REDIS_URL:-redis://redis:6379}
        DATABASE_URL: ${POSTGRES_URL:-psql://postgres:pwd111@postgres:5432/dvc}
        SECRET_KEY: ${SECRET_KEY:-"sjwx00s&zu5yz&r(fh4i7pi6c4ukf!9a17rdgyfbfwfo#w%9%0"}
        UI_URL: ${UI_URL:-http://localhost:3000}

        GITHUB_APP_ID: ${GITHUB_APP_ID:-}
        GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID:-}
        GITHUB_APP_SECRET_KEY: ${GITHUB_APP_SECRET_KEY:-}
        GITHUB_APP_PRIVATE_KEY_PEM: ${GITHUB_APP_PRIVATE_KEY_PEM:-}
        GITHUB_URL: ${GITHUB_URL:-}
        GITHUB_WEBHOOK_URL: ${GITHUB_WEBHOOK_URL:-http://localhost:8000/webhook/github/}
        GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET:-github_secret}

        GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID:-}
        GITLAB_SECRET_KEY: ${GITLAB_SECRET_KEY:-}
        GITLAB_URL: ${GITLAB_URL:-https://gitlab.com}
        GITLAB_WEBHOOK_URL: ${GITLAB_WEBHOOK_URL:-http://localhost:8000/webhook/gitlab/}
        GITLAB_WEBHOOK_SECRET: ${GITLAB_WEBHOOK_SECRET:-}

        BITBUCKET_CLIENT_ID: ${BITBUCKET_CLIENT_ID:-}
        BITBUCKET_SECRET_KEY: ${BITBUCKET_SECRET_KEY:-}
        BITBUCKET_API_URL: ${BITBUCKET_API_URL:-}
        BITBUCKET_URL: ${BITBUCKET_URL-http://localhost:8000/webhook/bitbucket/}
        BITBUCKET_WEBHOOK_URL: ${BITBUCKET_WEBHOOK_URL:-}

        MAX_VIEWS: ${MAX_VIEWS:-100}
        MAX_TEAMS: ${MAX_TEAMS:-10}

        # Minio/S3 storage
        ENABLE_BLOBVAULT: ${ENABLE_BLOBVAULT:-True}
        BLOBVAULT_AWS_ACCESS_KEY_ID: ${BLOBVAULT_AWS_ACCESS_KEY_ID:-minioadmin}
        BLOBVAULT_AWS_SECRET_ACCESS_ID: ${BLOBVAULT_AWS_SECRET_ACCESS_ID:-minioadmin}
        BLOBVAULT_ENDPOINT_URL: ${BLOBVAULT_ENDPOINT_URL:-http://minio:9000}
        BLOBVAULT_ENDPOINT_URL_FE: ${BLOBVAULT_ENDPOINT_URL_FE:-http://localhost:9000}
        BLOBVAULT_BUCKET: ${BLOBVAULT_BUCKET:-blobvault}
    ports:
      - 8000:8000
      - 3000:3000

  ui:
    image: ${STUDIO_UI_IMAGE}:${STUDIO_RELEASE_VERSION}
    restart: always
    network_mode: service:api
    environment:
      API_URL: ${API_URL:-http://localhost:8000/api}
      SCM_PROVIDERS: ${SCM_PROVIDERS:-github,gitlab,bitbucket}
      FLAGS: ${FLAGS:-}

      GITHUB_APP_NAME: ${GITHUB_APP_NAME:-}
      GITHUB_URL: ${GITHUB_URL:-https://github.com}
      GITLAB_URL: ${GITLAB_URL:-https://gitlab.com}
      BITBUCKET_URL: ${BITBUCKET_URL:-https://bitbucket.org}

      MAX_VIEWS: ${MAX_VIEWS:-100}
      MAX_TEAMS: ${MAX_TEAMS:-10}

  worker:
    command:
      - celery
      - worker
      - -Aviewer
      - -linfo
      - -Pthreads
      - -c4
    image: ${STUDIO_BACKEND_IMAGE}:${STUDIO_RELEASE_VERSION}
    restart: always
    deploy:
      replicas: 2
    environment:
      NO_MIGRATE_DB: "1"
      WAIT_FOR_MIGRATIONS: "1"
      <<: *base_settings

  beat:
    command:
      - celery
      - beat
      - -Aviewer
      - -linfo
      - -Sdjango_celery_beat.schedulers:DatabaseScheduler
    image: ${STUDIO_BACKEND_IMAGE}:${STUDIO_RELEASE_VERSION}
    restart: always
    environment:
      NO_MIGRATE_DB: "1"
      WAIT_FOR_MIGRATIONS: "1"
      <<: *base_settings
