version: "3.4"

services:
  api:
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    environment:
      ALLOWED_HOSTS: "*"
      UI_URL: http://localhost:3000
      SOCIAL_AUTH_REDIRECT_IS_HTTPS: "False"

      # legacy
      MIGRATE_DB: "1"
      LOGIN_REDIRECT_URL: http://localhost:3000/dashboard
      LOGIN_ERROR_URL: http://localhost:3000/
      LOGOUT_REDIRECT_URL: http://localhost:3000/
      CORS_ORIGIN_WHITELIST: http://localhost:3000/

      <<: &base_settings
        SECRET_KEY: ${SECRET_KEY:-"sjwx00s&zu5yz&r(fh4i7pi6c4ukf!9a17rdgyfbfwfo#w%9%0"}
        DATABASE_URL: ${POSTGRES_URL:-psql://postgres:pwd111@postgres:5432/dvc}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_SECRET_KEY: ${GITHUB_SECRET_KEY}
        GITHUB_WEBHOOK_URL: ${GITHUB_WEBHOOK_URL:-""}
        GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET:-""}
        # other services deps
        CELERY_BROKER_URL: ${REDIS_URL:-redis://redis:6379}
        CELERY_RESULT_BACKEND: ${REDIS_URL:-redis://redis:6379}
    ports:
      - 8000:8000
  ui:
    image: ${DVC_VIEWER_UI_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    environment:
      API_URL: http://localhost:8000/api
      FLAGS: ${FLAGS:-""}
    ports:
      - 3000:3000

  worker:
    command: ["celery", "worker", "-Aviewer", "-linfo", "-Pthreads", "-c4"]
    image: ${DVC_VIEWER_BACKEND_IMAGE}:${DVC_VIEWER_RELEASE_VERSION}
    deploy:
      replicas: 2
    environment:
      <<: *base_settings
