version: "3.4"

services:
  api:
    volumes:
      - $TLS_CA_DIRECTORY:/usr/local/share/ca-certificates

  ui:
    volumes:
      - $TLS_CA_DIRECTORY:/usr/local/share/ca-certificates

  worker:
    volumes:
      - $TLS_CA_DIRECTORY:/usr/local/share/ca-certificates

  beat:
    volumes:
      - $TLS_CA_DIRECTORY:/usr/local/share/ca-certificates
