version: "3.4"

services:
  traefik:
    image: traefik:banon
    command:
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
    network_mode: service:api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    labels:
      - traefik.http.routers.api.rule=((PathPrefix(`/api`)) || PathPrefix(`/webhook`) )
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=8000

      - traefik.http.routers.ui.rule=PathPrefix(`/`)
      - traefik.http.routers.ui.service=ui
      - traefik.http.services.ui.loadbalancer.server.port=3000
    extra_hosts:
      - "${STUDIO_HOSTNAME}:127.0.0.1"
    ports:
      - 80:80

  minio:
    labels:
      - traefik.http.routers.minio.rule=(PathPrefix(`/minio`))
      - traefik.http.middlewares.minio1.stripprefix.prefixes=/minio
      - traefik.http.routers.minio.middlewares=minio1@docker
