apiVersion: v1
kind: Service
metadata:
  name: dvc-viewer-postgres
  labels:
    app.kubernetes.io/name: dvc-viewer-postgres
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: postgres
    app.kubernetes.io/company: iterative.ai
spec:
  ports:
  - name: postgres
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: dvc-viewer-postgres
