apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvc-viewer-postgres-pv-claim
  labels:
    app.kubernetes.io/name: dvc-viewer-postgres-pv-claim
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/component: postgres
    app.kubernetes.io/company: iterative.ai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
