apiVersion: v1
kind: ConfigMap
metadata:
  name: dvc-viewer-config
  labels:
    app.kubernetes.io/name: dvc-viewer-config
    app.kubernetes.io/part-of: dvc-viewer
    app.kubernetes.io/company: iterative.ai
data:
  # Django option
  # https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts
  ALLOWED_HOSTS: '*'
  # API endpoint that is used by frontend
  # url, required
  API_URL: http://example.com/api
  # Debug flag is used for Django app
  # https://docs.djangoproject.com/en/3.0/ref/settings/#debug
  # string (python bool)
  DEBUG: "False"
  # Environment for the service
  ENV: prod
  # UI endpoint that is used by webapi
  # url, required
  UI_URL: http://example.com/ui
  # Django option
  # https://docs.djangoproject.com/en/3.0/ref/settings/#use-x-forwarded-host
  USE_X_FORWARDED_HOST: "True"
