name: Build AMI
on:
  push:
    branches: [main]
    paths:
      - packer/**
      - .github/workflows/build-ami.yml
  repository_dispatch:
    types: [ helm-release ]
  pull_request:
    paths:
      - packer/**
      - .github/workflows/build-ami.yml
permissions:
  contents: read
  id-token: write
jobs:
  build-ami:
    environment: aws
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::260760892802:role/studio-selfhosted-packer
          role-duration-seconds: 3600

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"

      - name: Run `packer init`
        id: init
        run: "packer init ./studio-selfhosted.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./studio-selfhosted.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./studio-selfhosted.pkr.hcl"
        env:
          PKR_VAR_skip_create_ami: ${{ github.event_name != 'pull_request' && 'false' || 'true' }}

